### ISSUE TITLE
oopmenu\sfmenu.vcx is in use and cannot be recompiled

### ISSUE THREAD

**Issue by pivoten-psherwood** [DougHennig/DeployFox#1]
I created an initial project and added two tasks.
1. Build an exe
2. Sign the exe

When I run it I get the error "oopmenu\sfmenu.vcx is in use and cannot be recompiled"

![image](https://github.com/user-attachments/assets/b9e433b6-72e8-4440-b395-ecc174631109)

If I click ignore I get the compile error.
![image](https://github.com/user-attachments/assets/75064dda-1d58-4dfc-8be9-9d6f5cc3dff6)

Clicking Yes on the dialog to view the log file does nothing.

![image](https://github.com/user-attachments/assets/4f364a86-7dbc-4feb-a67c-0a3c0c7f0592)

The project .err file has the following:

![image](https://github.com/user-attachments/assets/182ac7a9-9b7c-40f0-bbe3-9c7f6746da52)

**Comment by DougHennig** [comment]
Thanks for the bug report. Fixed in the latest release.
